//! Extracts every Rust snippet from `README.md` and `docs/USAGE.md` so the
//! test suite compiles them.
//!
//! `examples/tour.rs` runs the documented flows, but it is a *transcription*:
//! the guide can drift and the tour still compiles, because they are two
//! copies of the same code. This takes the documents themselves as input, so a
//! signature change that a snippet missed is a build failure rather than a
//! reader's problem. It caught six calls still passing a timeout argument
//! removed three commits earlier, and one `match` arm short of a field.
//!
//! A block that illustrates rather than runs — a list of signatures, an enum —
//! opts out with `<!-- doc-check: skip -->` on the line above its fence.

use std::{env, fs, path::PathBuf};

/// Bindings a fragment can assume. A snippet is written for a reader, so it
/// says `conn.send(..)` without the twenty lines that produced `conn`; this
/// supplies them. Nothing here runs — the generated functions are compiled and
/// never called — so binding a socket costs nothing.
const PRELUDE: &str = r#"
    fn save_to_flash(_: &[u8; 32]) {}
    fn load_from_flash() -> [u8; 32] { [0u8; 32] }
    let addr = "127.0.0.1:1";
    let identity = Identity::generate();
    let peer_public = *identity.public();
    let server_public = peer_public;
    let their_public = peer_public;
    let ticket: Ticket = Ticket::from_key([0u8; 32]);
    let key = [0u8; 32];
    let samples: Vec<u8> = Vec::new();
    let recording: Vec<u8> = Vec::new();
    let payload: Vec<u8> = Vec::new();
    let reading: Vec<u8> = Vec::new();
    let more: Vec<u8> = Vec::new();
    let data: Vec<u8> = Vec::new();
    let mut buf = vec![0u8; 2048];
    let conn = Connection::connect_psk(addr, b"scaffolding")?;
    let mut server = Endpoint::bind_psk(addr, b"scaffolding")?;
    let mut node = Endpoint::bind_psk(addr, b"scaffolding")?;
    let peer = server.connect(addr, None)?;
    let allow_list: Vec<[u8; 32]> = Vec::new();
"#;

fn main() {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..");
    let docs = ["README.md", "docs/USAGE.md"];

    let mut out = String::from(
        "// Generated by build.rs from the documentation. Do not edit.\n\
         use fectp::{Connection, Endpoint, Event, Identity, PayloadType, Result, Ticket};\n\
         use std::time::Duration;\n",
    );
    let mut count = 0usize;

    for doc in docs {
        let path = root.join(doc);
        println!("cargo:rerun-if-changed={}", path.display());
        // A packaged crate has no docs beside it; there is nothing to check.
        let Ok(text) = fs::read_to_string(&path) else {
            continue;
        };
        let lines: Vec<&str> = text.lines().collect();
        let mut i = 0;
        let mut nth = 0;
        while i < lines.len() {
            if !lines[i].starts_with("```rust") {
                i += 1;
                continue;
            }
            let skip = lines[i.saturating_sub(1)].contains("doc-check: skip");
            let start = i + 1;
            let mut j = start;
            while j < lines.len() && !lines[j].starts_with("```") {
                j += 1;
            }
            nth += 1;
            if !skip {
                count += 1;
                let name = format!("{}_{nth}", doc.replace(['.', '/', '-'], "_"));
                out.push_str(&format!(
                    "\n/// {doc}:{start}\nfn {name}() -> Result<()> {{{PRELUDE}\n{}\n    Ok(())\n}}\n",
                    lines[start..j].join("\n")
                ));
            }
            i = j;
        }
    }

    out.push_str(&format!("\npub const SNIPPETS_CHECKED: usize = {count};\n"));
    let dest = PathBuf::from(env::var("OUT_DIR").unwrap()).join("doc_snippets.rs");
    fs::write(dest, out).expect("write generated snippets");
}
